### ISSUE TITLE
Disconnection issue: token session or clevercloud autoscaler

### ISSUE THREAD

**Issue by Cethy** [dis-moi/backend#104]
[126-disconnection-issue-token-session-or-clevercloud-autoscaler](https://trello.com/c/g7cltpRb/126-disconnection-issue-token-session-or-clevercloud-autoscaler).

### Investigation results
- By default, clevercloud supports the session sharing between instances via a ["replicated file system"](https://www.clever-cloud.com/doc/php/php-apps/#use-redis-to-store-php-sessions) ;
- the app config does not use the default session handling :
```yml
# app/config/config.yml
framework:
    # ...
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
``` 

Since I cannot find more detailed data on how clevercloud actually handle the "replicated file system", I suppose it only supports the default session directory.

### Possible solutions
- Understand why the app use a non standard session handling and safely remove it ;
- Use "custom" session handling supporting multiple instances, like memcache/redis or db ;
